### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-cli#19]
Unhandled exception while running `virtool isolate`.

Likely due to sending too many requests to NCBI. Please verify by looking at `urllib` documentation and researching status code. Post information as reply to this issue.

May need to find more robust way to throttle requests as too many seem to be getting sent.

```
Job processing failed
job: <Job coro=<<coroutine object fetch_otu_isolates at 0x7f107c357830>>>
Traceback (most recent call last):
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/virtool_cli/isolate.py", line 84, in fetch_otu_isolates
    records, new_accessions = await asyncio.get_event_loop().run_in_executor(None, get_records, accessions, taxid)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/virtool_cli/isolate.py", line 144, in get_records
    id=taxid, idtype="acc"))
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 281, in elink
    return _open(cgi, variables)
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/Bio/Entrez/__init__.py", line 606, in _open
    handle = urlopen(cgi)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

**Comment by jakeale** [comment]
This is strange, I really thought I had found an interval that was safe enough for the requests. I'm finding that this is most likely to happen when there are no accessions in local cache, since this results in a `Entrez.elink` followed quickly by a `Entrez.fetch`.

**Comment by jakeale** [comment]
The HTTPError 'Retry-After' header has a value of 2 seconds, so [I made it automatically retry while adhering to this](https://github.com/jakeale/virtool-cli/commit/7b831038896d23bac0c348b9aa78bd4a05f4a2e7#diff-aee01e75cd9e104f1c3389e32c49f21809badb9fd4d47cf035626411ad876b20R144-R167), but I'm wondering if there's a cleaner way of doing this.
