### ISSUE TITLE
Gracefully handle KeyboardInterrupt in isolate subcommand

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool-cli#22]
Entering Ctrl+C while command is running results in messy unhandled exception:
```
^CJob processing failed
job: <Job coro=<<coroutine object fetch_otu_isolates at 0x7f109c23dc20>>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/virtool_cli/isolate.py", line 109, in fetch_otu_isolates
    new_id = await store_sequence(isolate_path, accession, accession_data, sequence_ids)
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/virtool_cli/isolate.py", line 230, in store_sequence
    async with aiofiles.open(os.path.join(path, new_id + ".json"), "w") as f:
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/home/igboyes/.venv/ref/lib/python3.7/site-packages/aiofiles/threadpool/__init__.py", line 78, in _open
    opener=opener,
KeyboardInterrupt

Aborted!
```
- [ ] use `try...except` to catch `KeyboardInterrupt` and close `aiojobs` scheduler
- [ ] handle `TaskCancelled` exception in coroutine that runs in scheduler
  - should any cleanup code by executed if the coroutine is cancelled part way through execution? (Document in issue)

**Comment by jakeale** [comment]
[This](https://github.com/jakeale/virtool-cli/commit/8029c4cbfa18ad777350892dd94324077d87c4c6#diff-aee01e75cd9e104f1c3389e32c49f21809badb9fd4d47cf035626411ad876b20R50-R54) appears to be enough to gracefully close the scheduler. I'm not encountering any `TaskCancelled` exceptions using this.
